name: UndeadWave
version: ${version}
authors: [Yukino_Akira]
main: com.akira.undeadwave.UndeadWave
api-version: 1.20
depend: [AkiraCore]

commands:
  arenapreset:
    permission: undeadwave.admin
    aliases: [ap]
  globalsettings:
    permission: undeadwave.admin
    aliases: [gs]
  undeadwave:
    permission: undeadwave.user
    aliases: [uw]

permissions:
  undeadwave.user:
    default: true
  undeadwave.admin:
    default: op