common_zombie:
  type: ZOMBIE
  display_name: "普通僵尸"
  health: 20
  damage: 6
  speed_bonus: 0
  available_round:
    from: 1
    to: 5
  weight: 100
  reward: 35
  equipment:
    weapon: EMPTY
    helmet: EMPTY
    chestplate: EMPTY
    leggings: EMPTY
    boots: EMPTY
  extra_modifiers: []

gold_zombie:
  type: ZOMBIE
  display_name: "黄金僵尸"
  health: 20
  damage: 10
  speed_bonus: 10
  available_round:
    from: 5
    to: 8
  weight: 100
  reward: 45
  equipment:
    weapon: GOLDEN_SWORD
    helmet: GOLDEN_HELMET
    chestplate: GOLDEN_CHESTPLATE
    leggings: GOLDEN_LEGGINGS
    boots: GOLDEN_BOOTS
  extra_modifiers: []

iron_zombie:
  type: ZOMBIE
  display_name: "铁桶僵尸"
  health: 20
  damage: 14
  speed_bonus: 20
  available_round:
    from: 8
    to: 12
  weight: 100
  reward: 55
  equipment:
    weapon: IRON_SWORD
    helmet: IRON_HELMET
    chestplate: IRON_CHESTPLATE
    leggings: IRON_LEGGINGS
    boots: IRON_BOOTS
  extra_modifiers: []

diamond_zombie:
  type: ZOMBIE
  display_name: "钻石僵尸"
  health: 20
  damage: 18
  speed_bonus: 30
  available_round:
    from: 12
    to: 999
  weight: 100
  reward: 65
  equipment:
    weapon: DIAMOND_SWORD
    helmet: DIAMOND_HELMET
    chestplate: DIAMOND_CHESTPLATE
    leggings: DIAMOND_LEGGINGS
    boots: DIAMOND_BOOTS
  extra_modifiers: []

speedster_zombie:
  type: ZOMBIE
  display_name: "飞翔僵尸"
  health: 40
  damage: 8
  speed_bonus: 60
  available_round:
    from: 6
    to: 8
  weight: 15
  reward: 90
  equipment:
    weapon: WOODEN_SHOVEL
    helmet: LEATHER_HELMET;shiny;color=WHITE
    chestplate: LEATHER_CHESTPLATE;shiny;color=WHITE
    leggings: LEATHER_LEGGINGS;shiny;color=WHITE
    boots: LEATHER_BOOTS;shiny;color=WHITE
  extra_modifiers: []

lightning_zombie:
  type: ZOMBIE
  display_name: "闪电僵尸"
  health: 40
  damage: 12
  speed_bonus: 100
  available_round:
    from: 11
    to: 999
  weight: 15
  reward: 100
  equipment:
    weapon: IRON_SHOVEL
    helmet: IRON_HELMET;shiny
    chestplate: LEATHER_CHESTPLATE;shiny
    leggings: LEATHER_LEGGINGS;shiny
    boots: IRON_BOOTS;shiny
  extra_modifiers: []

thunderblot_zombie:
  type: ZOMBIE
  display_name: "雷霆刺客"
  health: 50
  damage: 18
  speed_bonus: 20
  available_round:
    from: 7
    to: 10
  weight: 30
  reward: 110
  equipment:
    weapon: DIAMOND_AXE;shiny
    helmet: LEATHER_HELMET;color=RED
    chestplate: LEATHER_CHESTPLATE;color=RED
    leggings: LEATHER_LEGGINGS;color=RED
    boots: LEATHER_BOOTS;color=RED
  extra_modifiers: []

shadow_assassin_zombie:
  type: ZOMBIE
  display_name: "暗影刺客"
  health: 70
  damage: 24
  speed_bonus: 40
  available_round:
    from: 13
    to: 999
  weight: 20
  reward: 120
  equipment:
    weapon: NETHERITE_AXE;shiny
    helmet: LEATHER_HELMET;color=BLACK
    chestplate: LEATHER_CHESTPLATE;color=BLACK
    leggings: LEATHER_LEGGINGS;color=BLACK
    boots: LEATHER_BOOTS;color=BLACK
  extra_modifiers: []

rock_zombie:
  type: ZOMBIE
  display_name: "岩石僵尸"
  health: 30
  damage: 5
  speed_bonus: 0
  available_round:
    from: 3
    to: 6
  weight: 20
  reward: 50
  equipment:
    weapon: EMPTY
    helmet: IRON_HELMET
    chestplate: CHAINMAIL_CHESTPLATE
    leggings: CHAINMAIL_LEGGINGS
    boots: IRON_BOOTS
  extra_modifiers:
    - tank:GENERIC_KNOCKBACK_RESISTANCE:1.0:SET_BASE

tank_zombie:
  type: ZOMBIE
  display_name: "坦克僵尸"
  health: 40
  damage: 10
  speed_bonus: 0
  available_round:
    from: 10
    to: 999
  weight: 20
  reward: 70
  equipment:
    weapon: EMPTY
    helmet: DIAMOND_HELMET
    chestplate: NETHERITE_CHESTPLATE
    leggings: NETHERITE_LEGGINGS
    boots: DIAMOND_BOOTS
  extra_modifiers:
    - tank:GENERIC_KNOCKBACK_RESISTANCE:1.0:SET_BASE

common_skeleton:
  type: ZOMBIE
  display_name: "普通骷髅"
  health: 20
  damage: 4
  speed_bonus: 0
  available_round:
    from: 4
    to: 7
  weight: 30
  reward: 50
  equipment:
    weapon: BOW
    helmet: EMPTY
    chestplate: EMPTY
    leggings: EMPTY
    boots: EMPTY
  extra_modifiers: []

gold_skeleton:
  type: ZOMBIE
  display_name: "黄金骷髅"
  health: 20
  damage: 8
  speed_bonus: 15
  available_round:
    from: 7
    to: 10
  weight: 30
  reward: 65
  equipment:
    weapon: BOW
    helmet: GOLDEN_HELMET
    chestplate: GOLDEN_CHESTPLATE
    leggings: GOLDEN_LEGGINGS
    boots: GOLDEN_BOOTS
  extra_modifiers: []

iron_skeleton:
  type: ZOMBIE
  display_name: "铁桶骷髅"
  health: 20
  damage: 12
  speed_bonus: 30
  available_round:
    from: 10
    to: 999
  weight: 30
  reward: 80
  equipment:
    weapon: BOW
    helmet: IRON_HELMET
    chestplate: IRON_CHESTPLATE
    leggings: IRON_LEGGINGS
    boots: IRON_BOOTS
  extra_modifiers: []

impact_skeleton:
  type: ZOMBIE
  display_name: "冲击者"
  health: 40
  damage: 8
  speed_bonus: 20
  available_round:
    from: 7
    to: 999
  weight: 5
  reward: 100
  equipment:
    weapon: BOW;shiny;ench=punch:5
    helmet: LEATHER_HELMET;shiny;color=ORANGE
    chestplate: LEATHER_CHESTPLATE;shiny;color=YELLOW
    leggings: LEATHER_LEGGINGS;shiny;color=ORANGE
    boots: LEATHER_BOOTS;shiny;color=YELLOW
  extra_modifiers: []

sniper_skeleton:
  type: ZOMBIE
  display_name: "狙击手"
  health: 40
  damage: 18
  speed_bonus: 20
  available_round:
    from: 11
    to: 999
  weight: 5
  reward: 120
  equipment:
    weapon: BOW;shiny
    helmet: LEATHER_HELMET;shiny;color=BLACK
    chestplate: LEATHER_CHESTPLATE;shiny;color=BLACK
    leggings: LEATHER_LEGGINGS;shiny;color=BLACK
    boots: LEATHER_BOOTS;shiny;color=BLACK
  extra_modifiers: []