melee:
  bloody_blade:
    material: STONE_SWORD
    display_name: "鲜血之刃"
    description:
      - "刀刃沾着鲜红的血液，"
      - "似乎对鲜血有强烈的反应。"
    damage: 10
    life_steal:
      ratio: 20
      chance: 20
    crit:
      damage: 70
      chance: 40
    velocity_multiplier: 1.2
    sweep_damage_bonus: 0
    true_damage: false
    allow_sweep: false
    cost: 800

  vampiric_blade:
    material: IRON_SWORD
    display_name: "吸血鬼之刃"
    description:
      - "传说中吸血鬼的武器，"
      - "可将鲜血化作无尽的力量。"
    damage: 16
    life_steal:
      ratio: 18
      chance: 30
    crit:
      damage: 100
      chance: 70
    velocity_multiplier: 1.4
    sweep_damage_bonus: 0
    true_damage: false
    allow_sweep: false
    cost: 2000

  fate_sword:
    material: IRON_SWORD
    display_name: "命运之剑"
    description:
      - "紧握这把剑，闭上眼睛，"
      - "将一切交给命运来决定。"
    damage: 10
    life_steal:
      ratio: 0
      chance: 0
    crit:
      damage: 900
      chance: 40
    velocity_multiplier: 1.6
    sweep_damage_bonus: 0
    true_damage: false
    allow_sweep: true
    cost: 2200

  lucky_sword:
    material: STONE_SWORD
    display_name: "幸运之剑"
    description:
      - "每一刀都在赌，"
      - "偶尔能打出惊人的伤害。"
    damage: 8
    life_steal:
      ratio: 0
      chance: 0
    crit:
      damage: 600
      chance: 30
    velocity_multiplier: 1.3
    sweep_damage_bonus: 0
    true_damage: false
    allow_sweep: false
    cost: 500

  wood_knife:
    material: WOODEN_SWORD
    display_name: "木制匕首"
    description:
      - "这是你的第一把剑，"
      - "能帮助你驱魔降妖。"
    damage: 6
    life_steal:
      ratio: 0
      chance: 0
    crit:
      damage: 90
      chance: 45
    velocity_multiplier: 1.0
    sweep_damage_bonus: 0
    true_damage: false
    allow_sweep: false
    cost: 50

  iron_knife:
    material: IRON_SWORD
    display_name: "铁制匕首"
    description:
      - "精心锻造而成的好剑，"
      - "材料升级后战力更强了。"
    damage: 10
    life_steal:
      ratio: 0
      chance: 0
    crit:
      damage: 120
      chance: 60
    velocity_multiplier: 1.25
    sweep_damage_bonus: 0
    true_damage: false
    allow_sweep: false
    cost: 400

  diamond_knife:
    material: DIAMOND_SWORD
    display_name: "钻石匕首"
    description:
      - "使用坚硬的钻石制成，"
      - "虽然昂贵，但相信它值得。"
    damage: 18
    life_steal:
      ratio: 0
      chance: 0
    crit:
      damage: 150
      chance: 75
    velocity_multiplier: 1.75
    sweep_damage_bonus: 0
    true_damage: false
    allow_sweep: true
    cost: 1200

  shock_blade:
    material: WOODEN_SWORD
    display_name: "击退剑"
    description:
      - "短暂击退敌人，"
      - "为自己争取时间。"
    damage: 14
    life_steal:
      ratio: 0
      chance: 0
    crit:
      damage: 100
      chance: 45
    velocity_multiplier: 3.0
    sweep_damage_bonus: 0
    true_damage: false
    allow_sweep: true
    cost: 1200

  storm_blade:
    material: IRON_SWORD
    display_name: "风暴之剑"
    description:
      - "如同风暴席卷万物而去，"
      - "为下一轮战斗争取时间。"
    damage: 18
    life_steal:
      ratio: 10
      chance: 8
    crit:
      damage: 200
      chance: 75
    velocity_multiplier: 5.0
    sweep_damage_bonus: 0
    true_damage: false
    allow_sweep: true
    cost: 2200

  long_sword:
    material: STONE_SWORD
    display_name: "长剑"
    description:
      - "这把剑格外地长，"
      - "也许具备横扫千军潜力。"
    damage: 12
    life_steal:
      ratio: 0
      chance: 0
    crit:
      damage: 90
      chance: 35
    velocity_multiplier: 1.15
    sweep_damage_bonus: 30
    true_damage: false
    allow_sweep: true
    cost: 600

  wind_sword:
    material: IRON_SWORD
    display_name: "风之剑"
    description:
      - "一把风神眷顾的剑，"
      - "横扫战力十分可观。"
    damage: 19
    life_steal:
      ratio: 0
      chance: 0
    crit:
      damage: 110
      chance: 50
    velocity_multiplier: 1.45
    sweep_damage_bonus: 105
    true_damage: false
    allow_sweep: true
    cost: 1200

  whirlwind_sword:
    material: IRON_SWORD
    display_name: "旋风剑"
    description:
      - "刮倒万物的存在，"
      - "横扫千军，胜券在握。"
    damage: 26
    life_steal:
      ratio: 8
      chance: 8
    crit:
      damage: 180
      chance: 75
    velocity_multiplier: 1.6
    sweep_damage_bonus: 180
    true_damage: false
    allow_sweep: true
    cost: 2800

  piercing_knife:
    material: WOODEN_SWORD
    display_name: "穿透之刃"
    description:
      - "以一股神秘的力量，"
      - "击碎盔甲的防御。"
    damage: 8
    life_steal:
      ratio: 0
      chance: 0
    crit:
      damage: 60
      chance: 40
    velocity_multiplier: 1.0
    sweep_damage_bonus: 0
    true_damage: true
    allow_sweep: false
    cost: 800

  true_knife:
    material: STONE_SWORD
    display_name: "真·匕首"
    description:
      - "以未知物质锻造而成，"
      - "轻松击破厚实的盔甲。"
    damage: 12
    life_steal:
      ratio: 0
      chance: 0
    crit:
      damage: 70
      chance: 55
    velocity_multiplier: 1.2
    sweep_damage_bonus: 50
    true_damage: true
    allow_sweep: true
    cost: 1600

  truth_sword:
    material: IRON_SWORD
    display_name: "真理之剑"
    description:
      - "以真理的力量，"
      - "击碎遇到的一切障碍。"
    damage: 16
    life_steal:
      ratio: 15
      chance: 8
    crit:
      damage: 100
      chance: 70
    velocity_multiplier: 1.5
    sweep_damage_bonus: 100
    true_damage: true
    allow_sweep: true
    cost: 2800

ranged:
  fire_launcher:
    material: "STONE_SHOVEL"
    display_name: "火焰发射器"
    description:
      - "喷出熊熊火焰，"
      - "制造范围性伤害。"
    damage: 14.0
    crit_damage: 70
    crit_chance: 45
    cooldown_ticks: 15
    particle:
      type: "LAVA"
    sound:
      type: "ITEM_FIRECHARGE_USE"
      volume: 1.0
    max_distance: 8
    max_target_total: 8
    step_length: 0.5
    max_durability: 240
    hit_box_multiplier: 1.0
    piercing: true
    repeat_hit: false
    cost: 1600

  lava_launcher:
    material: "GOLDEN_SHOVEL"
    display_name: "岩浆发射器"
    description:
      - "喷出炙热的岩浆，"
      - "对敌人造成致命打击。"
    damage: 16.0
    crit_damage: 120
    crit_chance: 60
    cooldown_ticks: 15
    particle:
      type: "LAVA"
      count: 2
    sound:
      type: "ITEM_FIRECHARGE_USE"
      volume: 1.0
    max_distance: 12
    max_target_total: 16
    step_length: 0.5
    max_durability: 300
    hit_box_multiplier: 1.0
    piercing: true
    repeat_hit: false
    cost: 3800

  ancient_rocket_launcher:
    material: "DIAMOND_SHOVEL"
    display_name: "远古火箭筒"
    description:
      - "让人魂飞魄散的强者，"
      - "在古战场上所向披靡。"
    damage: 35.0
    crit_damage: 130
    crit_chance: 70
    cooldown_ticks: 50
    particle:
      type: "EXPLOSION_HUGE"
    sound:
      type: "ENTITY_GENERIC_EXPLODE"
      volume: 1.0
    max_distance: 20
    max_target_total: 16
    step_length: 2.0
    max_durability: 200
    hit_box_multiplier: 1.0
    piercing: true
    repeat_hit: false
    cost: 3800

  rocket_launcher:
    material: "STONE_SHOVEL"
    display_name: "火箭筒"
    description:
      - "硕大的肌肉，"
      - "激情的发射。"
    damage: 28.0
    crit_damage: 80
    crit_chance: 50
    cooldown_ticks: 70
    particle:
      type: "EXPLOSION_HUGE"
    sound:
      type: "ENTITY_GENERIC_EXPLODE"
      volume: 1.0
    max_distance: 12
    max_target_total: 10
    step_length: 2.0
    max_durability: 120
    hit_box_multiplier: 1.0
    piercing: true
    repeat_hit: false
    cost: 1800

  fate_gun:
    material: "IRON_PICKAXE"
    display_name: "命运之枪"
    description:
      - "相信命运的指引，"
      - "把一切交给命运。"
    damage: 11.0
    crit_damage: 580
    crit_chance: 35
    cooldown_ticks: 5
    particle:
      type: "GLOW"
    sound:
      type: "BLOCK_BAMBOO_HIT"
      volume: 2.0
    max_distance: 35
    max_target_total: 1
    step_length: 1.0
    max_durability: 360
    hit_box_multiplier: 1.0
    piercing: false
    repeat_hit: false
    cost: 1400

  gambler_gun:
    material: "WOODEN_PICKAXE"
    display_name: "赌徒之枪"
    description:
      - "相信自己的运气，"
      - "体验一把赌狗的快乐。"
    damage: 8.0
    crit_damage: 430
    crit_chance: 20
    cooldown_ticks: 7
    particle:
      type: "CRIT_MAGIC"
    sound:
      type: "BLOCK_BAMBOO_HIT"
      volume: 1.0
    max_distance: 25
    max_target_total: 1
    step_length: 1.0
    max_durability: 270
    hit_box_multiplier: 1.0
    piercing: false
    repeat_hit: false
    cost: 700

  copper_miner:
    material: "STONE_PICKAXE"
    display_name: "青铜矿工"
    description:
      - "上等的材料，"
      - "不俗的输出。"
    damage: 9.0
    crit_damage: 100
    crit_chance: 25
    cooldown_ticks: 7
    particle:
      type: "REDSTONE"
      count: 1
      data_type: "dust"
      color: [ 100, 40, 40 ]
      size: 1.0
    sound:
      type: "BLOCK_METAL_PLACE"
      volume: 1.0
    max_distance: 20
    max_target_total: 1
    step_length: 1.0
    max_durability: 240
    hit_box_multiplier: 1.0
    piercing: false
    repeat_hit: false
    cost: 700

  gold_miner:
    material: "GOLDEN_PICKAXE"
    display_name: "黄金矿工"
    description:
      - "黄金的信仰，"
      - "黄金的输出。"
    damage: 16.0
    crit_damage: 140
    crit_chance: 45
    cooldown_ticks: 5
    particle:
      type: "REDSTONE"
      count: 1
      data_type: "dust"
      color: [ 255, 255, 0 ]
      size: 2.0
    sound:
      type: "BLOCK_METAL_PLACE"
      volume: 1.0
    max_distance: 30
    max_target_total: 1
    step_length: 1.0
    max_durability: 360
    hit_box_multiplier: 1.0
    piercing: false
    repeat_hit: false
    cost: 2200

  netherite_miner:
    material: "NETHERITE_PICKAXE"
    display_name: "合金矿工"
    description:
      - "源自下界合金的力量，"
      - "满足你对攻速的一切想象。"
    damage: 23.0
    crit_damage: 180
    crit_chance: 65
    cooldown_ticks: 3
    particle:
      type: "REDSTONE"
      count: 1
      data_type: "dust"
      color: [ 128, 128, 128 ]
      size: 3.0
    sound:
      type: "BLOCK_METAL_PLACE"
      volume: 1.0
    max_distance: 40
    max_target_total: 1
    step_length: 1.0
    max_durability: 500
    hit_box_multiplier: 1.0
    piercing: false
    repeat_hit: false
    cost: 4700

  pistol:
    material: "WOODEN_HOE"
    display_name: "手枪"
    description:
      - "这是你的第一把枪，"
      - "与你并肩作战的队友。"
    damage: 6.0
    crit_damage: 60
    crit_chance: 35
    cooldown_ticks: 10
    particle:
      type: "CRIT"
    sound: null
    max_distance: 20
    max_target_total: 1
    step_length: 1.0
    max_durability: 160
    hit_box_multiplier: 1.0
    piercing: false
    repeat_hit: false
    cost: 50

  gold_pistol:
    material: "GOLDEN_HOE"
    display_name: "黄金手枪"
    description:
      - "高纯度黄金的加持下，"
      - "战力得到显著提升。"
    damage: 12.0
    crit_damage: 70
    crit_chance: 50
    cooldown_ticks: 8
    particle:
      type: "BLOCK_DUST"
      count: 1
      data_type: "block"
      material: "GOLD_BLOCK"
    sound:
      type: "BLOCK_STONE_PLACE"
      volume: 1.0
    max_distance: 30
    max_target_total: 1
    step_length: 1.0
    max_durability: 240
    hit_box_multiplier: 1.0
    piercing: false
    repeat_hit: false
    cost: 500

  diamond_shotgun:
    material: "DIAMOND_HOE"
    display_name: "钻石霰弹枪"
    description:
      - "钻石加成，值得信赖，"
      - "瞬间制造范围巨额伤害。"
    damage: 18.0
    crit_damage: 120
    crit_chance: 65
    cooldown_ticks: 30
    particle:
      type: "CLOUD"
      count: 20
      offset_x: 1.0
      offset_y: 1.0
      offset_z: 1.0
      extra: 0.1
    sound:
      type: "ENTITY_GENERIC_EXPLODE"
      volume: 2.0
    max_distance: 4
    max_target_total: 12
    step_length: 1.0
    max_durability: 180
    hit_box_multiplier: 2.0
    piercing: true
    repeat_hit: true
    cost: 4200

  shotgun:
    material: "IRON_HOE"
    display_name: "霰弹枪"
    description:
      - "非常适合贴脸开大，"
      - "瞬间制造范围大额伤害。"
    damage: 12.0
    crit_damage: 70
    crit_chance: 35
    cooldown_ticks: 40
    particle:
      type: "CLOUD"
      count: 10
      offset_x: 1.0
      offset_y: 1.0
      offset_z: 1.0
      extra: 0.1
    sound:
      type: "ENTITY_GENERIC_EXPLODE"
      volume: 2.0
    max_distance: 4
    max_target_total: 6
    step_length: 1.0
    max_durability: 120
    hit_box_multiplier: 2.0
    piercing: true
    repeat_hit: true
    cost: 700

  sniper:
    material: "WOODEN_SHOVEL"
    display_name: "狙击枪"
    description:
      - "远程精准打击，"
      - "露头就秒。"
    damage: 24.0
    crit_damage: 70
    crit_chance: 40
    cooldown_ticks: 30
    particle:
      type: "SMOKE_NORMAL"
    sound:
      type: "BLOCK_GRAVEL_STEP"
      volume: 2.0
    max_distance: 60
    max_target_total: 2
    step_length: 1.0
    max_durability: 140
    hit_box_multiplier: 1.0
    piercing: true
    repeat_hit: false
    cost: 1400

  infernal_sniper:
    material: "NETHERITE_SHOVEL"
    display_name: "炼狱狙击枪"
    description:
      - "藏于暗处打击敌人，"
      - "接受来自地狱的力量。"
    damage: 45.0
    crit_damage: 100
    crit_chance: 60
    cooldown_ticks: 20
    particle:
      type: "SOUL_FIRE_FLAME"
    sound:
      type: "BLOCK_GRAVEL_STEP"
      volume: 2.0
    max_distance: 80
    max_target_total: 3
    step_length: 1.0
    max_durability: 260
    hit_box_multiplier: 1.0
    piercing: true
    repeat_hit: false
    cost: 3000